# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '管理分类界面.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import jl,hy,kc,dd,md

class Ui_Form(object):
    def setupUi(self, Form):
        self.form=Form
        Form.setObjectName("Form")
        Form.resize(597, 493)
        window_pale = QtGui.QPalette()
        window_pale.setBrush(Form.backgroundRole(), QtGui.QBrush(QtGui.QPixmap("3.jpg")))
        Form.setPalette(window_pale)
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(480, 420, 93, 28))
        self.pushButton_5.setObjectName("pushButton_5")

        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setGeometry(QtCore.QRect(170, 60, 241, 341))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")

        self.pushButton = QtWidgets.QPushButton(self.splitter)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.splitter)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.splitter)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.splitter)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.splitter)
        self.pushButton_6.setObjectName("pushButton_6")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "优威健身会馆"))
        self.pushButton_5.setText(_translate("Form", "退出管理"))
        self.pushButton_5.clicked.connect(self.first)
        self.pushButton.setText(_translate("Form", "教练管理信息"))
        self.pushButton.clicked.connect(self.jl)
        self.pushButton_2.setText(_translate("Form", "会员管理信息"))
        self.pushButton_2.clicked.connect(self.hy)
        self.pushButton_3.setText(_translate("Form", "课程管理信息"))
        self.pushButton_3.clicked.connect(self.kc)
        self.pushButton_4.setText(_translate("Form", "订单管理信息"))
        self.pushButton_4.clicked.connect(self.dd)
        self.pushButton_6.setText(_translate("Form", "门店管理信息"))
        self.pushButton_6.clicked.connect(self.md)
    def first(self):
        self.form.close()
    def md(self):
        x = QtWidgets.QDialog()
        ui = md.Ui_Form()
        ui.setupUi(x)
        x.show()
        x.exec_()
        self.form.show()
    def jl(self):
        x = QtWidgets.QDialog()
        ui = jl.Ui_Form()
        ui.setupUi(x)
        x.show()
        x.exec_()
        self.form.show()
    def hy(self):
        x = QtWidgets.QDialog()
        ui = hy.Ui_Form()
        ui.setupUi(x)
        x.show()
        x.exec_()
        self.form.show()
    def kc(self):
        x = QtWidgets.QDialog()
        ui = kc.Ui_Form()
        ui.setupUi(x)
        x.show()
        x.exec_()
        self.form.show()
    def dd(self):
        x = QtWidgets.QDialog()
        ui = dd.Ui_Form()
        ui.setupUi(x)
        x.show()
        x.exec_()
        self.form.show()

import sys
if __name__ == '__main__':

    app=QtWidgets.QApplication(sys.argv)
    win = QtWidgets.QMainWindow()
    my=Ui_Form()
    my.setupUi(win)
    win.show()
    sys.exit(app.exec_())