# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '图表显示界面.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import pymysql
class Ui_Form(object):
    def __init__(self):
        self.col_num=5
        self.row_num=5
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1125, 646)
        window_pale = QtGui.QPalette()
        window_pale.setBrush(Form.backgroundRole(), QtGui.QBrush(QtGui.QPixmap("6.jpg")))
        Form.setPalette(window_pale)
        self.form=Form
        self.tablewidget(Form)
        self.button0(Form)
        self.linedit0(Form)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def tablewidget(self,Form):
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(40, 50, 1041, 271))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(self.col_num)
        self.tableWidget.setRowCount(self.row_num)

        lst=['教练编号','性别','姓名','工作门店','奖金']
        self.tableWidget.setHorizontalHeaderLabels(lst)  # 垂直标题

    def button0(self,Form):
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(40, 10, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 330, 1041, 89))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(290, 520, 501, 121))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 4, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 1, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 3, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setGeometry(QtCore.QRect(40, 430, 1041, 31))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")

    def linedit0(self,Form):
        self.lineEdit = QtWidgets.QLineEdit(self.splitter)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.splitter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.splitter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.splitter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.splitter)
        self.lineEdit_5.setObjectName("lineEdit_5")


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "教练表"))
        self.pushButton.setText(_translate("Form", "返回"))
        self.pushButton.clicked.connect(self.turn)
        self.pushButton_5.setText(_translate("Form", "删除"))
        self.pushButton_5.clicked.connect(self.delete)
        self.pushButton_2.setText(_translate("Form", "查询"))
        self.pushButton_2.clicked.connect(self.select)
        self.pushButton_3.setText(_translate("Form", "修改"))
        self.pushButton_3.clicked.connect(self.update)
        self.pushButton_4.setText(_translate("Form", "添加"))
        self.pushButton_4.clicked.connect(self.add)
    def turn(self):
        self.form.close()
    def clear_all(self):
        for i in range(self.row_num):
            for j in range(self.col_num):
                item = QtWidgets.QTableWidgetItem('')
                self.tableWidget.setItem(i, j, item)  # 设置表格中的值
    def setvalue(self,result):
        self.clear_all()
        if len(result)==0:
            print('没有查到任何值')
        else:
            self.row_num=len(result)
            self.col_num=len(result[0])
            self.tableWidget.setColumnCount(self.col_num)
            self.tableWidget.setRowCount(self.row_num)
            row=0
            for i in result:
                col=0
                for j in i:
                    item=QtWidgets.QTableWidgetItem(str(j))
                    self.tableWidget.setItem(row,col,item)
                    col+=1
                row+=1

    def select(self):
        if (len(self.lineEdit.text()) == 0 and
                len(self.lineEdit_2.text()) == 0 and
                len(self.lineEdit_3.text()) == 0 and
                len(self.lineEdit_4.text()) == 0 and
                len(self.lineEdit_5.text()) == 0):
            db = pymysql.connect(host='localhost', port=3306, user='root',
                                 passwd='123456', db='train', charset='utf8')
            print('数据库连接成功')
            cur = db.cursor()
            sql = "select * from 教练"
            cur.execute(sql)
            result=cur.fetchall()
            self.setvalue(result)
        else:
            db = pymysql.connect(host='localhost', port=3306, user='root',
                                 passwd='123456', db='train', charset='utf8')
            print('数据库连接成功')
            cur = db.cursor()
            if len(self.lineEdit.text()) != 0:
                sql = "select * from 教练 where 教练编号=%s" % (self.lineEdit.text())
                cur.execute(sql)
            elif len(self.lineEdit_2.text()) != 0:
                sql = "select * from 教练 where 性别='%s'" % (self.lineEdit_2.text())
                cur.execute(sql)
            elif len(self.lineEdit_3.text()) != 0:
                sql = "select * from 教练 where 姓名='%s'" % (self.lineEdit_3.text())
                cur.execute(sql)
            else:
                sql = "select * from 教练 where 工作门店='%s'" % (self.lineEdit_4.text())
                cur.execute(sql)
            result = cur.fetchall()
            self.setvalue(result)


    def update(self):
        db = pymysql.connect(host='localhost', port=3306, user='root',
                                 passwd='123456', db='train', charset='utf8')
        print('数据库连接成功')
        cur = db.cursor()
        if len(self.lineEdit_2.text())!=0:
            sql = "update 教练 set 性别='%s' where 教练编号=%s"%(self.lineEdit_2.text(),self.lineEdit.text())
            cur.execute(sql)
        if len(self.lineEdit_3.text())!=0:
            sql = "update 教练 set 姓名='%s' where 教练编号=%s"%(self.lineEdit_3.text(),self.lineEdit.text())
            cur.execute(sql)
        if len(self.lineEdit_4.text())!=0:
            sql = "update 教练 set 工作门店='%s' where 教练编号=%s"%(self.lineEdit_4.text(),self.lineEdit.text())
            cur.execute(sql)
        if len(self.lineEdit_5.text())!=0:
            print('$$$$$$')
            sql = "update 教练 set 奖金=%s where 教练编号=%s"%(self.lineEdit_5.text(),self.lineEdit.text())
            cur.execute(sql)
        db.commit()
        cur.close()
        db.close()





    def add(self):
        try:
            db = pymysql.connect(host='localhost', port=3306, user='root',
                                 passwd='123456', db='train', charset='utf8')
            print('数据库连接成功')
            data=(self.lineEdit.text(),self.lineEdit_2.text(),self.lineEdit_3.text(),self.lineEdit_4.text(),self.lineEdit_5.text())
            cur = db.cursor()
            sql = "insert into 教练 values(%s,%s,%s,%s,%s)"
            cur.execute(sql,data)
            db.commit()
            cur.close()
            db.close()
        except pymysql.Error as e:
            print(e)

    def delete(self):
        db = pymysql.connect(host='localhost', port=3306, user='root',
                                 passwd='123456', db='train', charset='utf8')
        print('数据库连接成功')
        cur = db.cursor()
        data=self.lineEdit.text()
        sql = "delete  from 教练 where 教练编号=%s"
        cur.execute(sql,data)
        db.commit()
        cur.close()
        db.close()
import sys
if __name__ == '__main__':

    app=QtWidgets.QApplication(sys.argv)
    win = QtWidgets.QMainWindow()
    my=Ui_Form()
    my.setupUi(win)
    win.show()
    sys.exit(app.exec_())