# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '登陆界面.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql
import sys
import views
import choose

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.mainwindow=MainWindow
        self.name=''
        self.password=''
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(420, 340)
        #设置背景图片
        window_pale=QtGui.QPalette()
        window_pale.setBrush(MainWindow.backgroundRole(),QtGui.QBrush(QtGui.QPixmap("0.jpg")))
        MainWindow.setPalette(window_pale)

        self.button0(MainWindow)
        self.lineedit0(MainWindow)
        self.label0(MainWindow)
        self.checkbox0(MainWindow)
        self.first()
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def button0(self,MainWindow):
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(180, 270, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(290, 270, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
    def lineedit0(self,MainWindow):
        # 门店输入狂
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(150, 100, 191, 21))
        self.lineEdit.setObjectName("lineEdit")
        # 密码输入狂
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setGeometry(QtCore.QRect(150, 153, 191, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
    def label0(self,MainWindow):
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 100, 72, 15))
        self.label.setStyleSheet("color: rgb(225, 85, 0);\n""font: 11pt \"Agency FB\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 150, 71, 21))
        self.label_2.setStyleSheet("color: rgb(225, 85, 0);\n""font: 11pt \"Agency FB\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 30, 351, 31))
        self.label_3.setStyleSheet("color: rgb(0, 0, 255);\n"
"font: 20pt \"楷体\";\n"
"")
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
    def checkbox0(self,MainWindow):
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(150, 200, 141, 19))
        self.checkBox.setObjectName("checkBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 443, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

    def first(self):
        self.name = self.lineEdit.text()  # 得到用户名的输入值
        self.password = self.lineEdit_2.text()  # 得到密码的输入值
        self.mainwindow.hide()
        x=QtWidgets.QDialog()
        ui=views.Ui_Form()
        ui.setupUi(x)
        x.show()
        x.exec_()
        if self.checkBox.checkState()==0:
            self.lineEdit.setText('')
            self.lineEdit_2.setText('')
        else:
            self.lineEdit.setText(self.name)
            self.lineEdit_2.setText('')
        self.mainwindow.show()
    def choose_page(self):
        self.name = self.lineEdit.text()  # 得到用户名的输入值
        self.password = self.lineEdit_2.text()  # 得到密码的输入值
        self.mainwindow.hide()
        x = QtWidgets.QDialog()
        ui =choose.Ui_Form()
        ui.setupUi(x)
        x.show()
        x.exec_()
        if self.checkBox.checkState() == 0:
            self.lineEdit.setText('')
            self.lineEdit_2.setText('')
        else:
            self.lineEdit.setText(self.name)
            self.lineEdit_2.setText('')
        self.mainwindow.show()
        self.first()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "管理员登录"))
        self.pushButton.setText(_translate("MainWindow", "登录"))
        self.pushButton.clicked.connect(self.register)

        self.pushButton_2.setText(_translate("MainWindow", "返回"))
        self.pushButton_2.clicked.connect(self.first)
        self.label.setText(_translate("MainWindow", "门店名"))
        self.label_2.setText(_translate("MainWindow", "密  码"))
        self.label_3.setText(_translate("MainWindow", "train"))
        self.checkBox.setText(_translate("MainWindow", "记住"))
    def register(self):
        self.name = self.lineEdit.text()  # 得到用户名的输入值
        self.password = self.lineEdit_2.text()  # 得到密码的输入值
        if len(self.name) != 0 and len(self.password) != 0:
            try:
                db = pymysql.connect(host='localhost', port=3306, user='root',
                                 passwd='123456', db='train', charset='utf8')
                print('数据库连接成功')
                cur = db.cursor()
                sql = "select * from 门店"
                cur.execute(sql)
                result = cur.fetchall()
                sign = 0
                for i in result:
                    if self.name == i[0]:
                        if self.password == i[3]:
                            sign = 1
                            break
                        sign = 2
                        break
                    else:
                        sign = 3
                if sign == 1:
                    self.choose_page()
                elif sign == 2:
                    msg_box = QtWidgets.QMessageBox(QtWidgets.QMessageBox.Warning, '警告', '密码错误')
                    msg_box.show()
                    msg_box.exec_()
                else:
                    msg_box = QtWidgets.QMessageBox(QtWidgets.QMessageBox.Warning, '警告', '用户不存在，登陆失败')
                    msg_box.show()
                    msg_box.exec_()
            except pymysql.Error as e:
                msg_box = QtWidgets.QMessageBox(QtWidgets.QMessageBox.Warning, '警告', str(e))
                msg_box.show()
                msg_box.exec_()
        else:
            msg_box = QtWidgets.QMessageBox(QtWidgets.QMessageBox.Warning, '警告', '用户名和密码都不能为空')
            msg_box.show()
            msg_box.exec_()


if __name__ == '__main__':

    app=QtWidgets.QApplication(sys.argv)
    win = QtWidgets.QMainWindow()
    my=Ui_MainWindow()
    my.setupUi(win)
    win.show()
    sys.exit(app.exec_())
