# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '视图界面.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(792, 596)
        window_pale = QtGui.QPalette()
        window_pale.setBrush(Form.backgroundRole(), QtGui.QBrush(QtGui.QPixmap("1.jpg")))
        Form.setPalette(window_pale)
        self.row=100
        self.col=0
        self.form=Form
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(40, 40, 701, 291))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setRowCount(10)

        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(320, 360, 141, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(570, 360, 141, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(570, 510, 141, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(60, 360, 141, 41))
        self.pushButton_4.setObjectName("pushButton_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "尊敬的通店会员您好"))
        self.pushButton.setText(_translate("Form", "课程一览"))
        self.pushButton.clicked.connect(self.kcview)
        self.pushButton_2.setText(_translate("Form", "教练一览"))
        self.pushButton_2.clicked.connect(self.jlview)
        self.pushButton_3.setText(_translate("Form", "管理信息"))
        self.pushButton_3.clicked.connect(self.go)
        self.pushButton_4.setText(_translate("Form", "门店一览"))
        self.pushButton_4.clicked.connect(self.mdview)
    def go(self):
        self.form.close()
    def clear(self):
        for i in range(self.row):
            for j in range(self.col):
                item = QtWidgets.QTableWidgetItem('')
                self.tableWidget.setItem(i, j, item)  # 设置表格中的值
    def kcview(self):

        db = pymysql.connect(host='localhost', port=3306, user='root',
                                 passwd='123456', db='train', charset='utf8')
        print('数据库连接成功')
        cur = db.cursor()
        sql = "select * from 课程表"
        cur.execute(sql)
        result=cur.fetchall()
        print(result)
        self.set_value(result)
        lst = ['课程名', '课程教练', '课程类型', '课程教练', '课程价格']
        self.tableWidget.setHorizontalHeaderLabels(lst)  # 垂直标题

    def jlview(self):
        lst = ['姓名', '性别', '工作门店']
        self.tableWidget.setHorizontalHeaderLabels(lst)  # 垂直标题
        db = pymysql.connect(host='localhost', port=3306, user='root',
                                 passwd='123456', db='train', charset='utf8')
        print('数据库连接成功')
        cur = db.cursor()
        sql = "select * from 教练表"
        cur.execute(sql)
        result = cur.fetchall()
        self.set_value(result)

    def mdview(self):
        lst = ['门店名称', '门店地址', '门店电话']
        self.tableWidget.setHorizontalHeaderLabels(lst)  # 垂直标题
        db = pymysql.connect(host='localhost', port=3306, user='root',
                                 passwd='123456', db='train', charset='utf8')
        print('数据库连接成功')
        cur = db.cursor()
        sql = "select * from 门店表"
        cur.execute(sql)
        result = cur.fetchall()
        self.set_value(result)
    def set_value(self,result):
        self.clear()
        self.row=len(result)
        self.col=len(result[0])
        self.tableWidget.setColumnCount(self.col)#设置列数
        self.tableWidget.setRowCount(self.row)#设置行数
        row=0       #行标
        for i in result:
            col=0   #列标
            for j in i:
                item=QtWidgets.QTableWidgetItem(str(j))
                self.tableWidget.setItem(row,col,item)      #设置表格中的值
                col+=1
            row+=1
if __name__ == '__main__':
    import sys
    app=QtWidgets.QApplication(sys.argv)
    win = QtWidgets.QMainWindow()
    my=Ui_Form()
    my.setupUi(win)
    win.show()
    sys.exit(app.exec_())